import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-[#FFF7E8] to-[#F9F0CF] min-h-screen`}
      >
        {/* Top logo appears on all pages except login/register */}
        {/* eslint-disable-next-line react/no-unknown-property */}
        <div>
          {/** Client wrapper decides visibility by pathname */}
          {/* @ts-expect-error Server-Client boundary */}
          {require("@/components/ui/TopLogo").default?.()}
        </div>
        {children}
      </body>
    </html>
  );
}
